- .gitignore
- PR-template.md
adds pr-template to project root directory & adds .vscode to .gitignore
NA
> adds pr-template to project root directory & adds .vscode to .gitignore

- frontend/components/Counter.tsx
- frontend/package.json
- frontend/pages/_app.tsx
- frontend/utils/theme.js
- frontend/yarn.lock
I wrapped our Application with a `<ThemeProvider />` component as described in: 
https://rebassjs.org/theming
The shades of colors were taken from: https://palx.jxnblk.com
I modified the `<Counter />` component to illustrate usage of theme variables
> wrap App with ThemeProvider HOC

- frontend/now.json
this is the configuration file needed to deploy our next.js frontend to `now`
more information can be found in their docs: https://zeit.co/examples/nextjs
> added now.json file for configuring deployment

- frontend/components/forms/TextArea.tsx
This was the initial commit for the text-area component, but I intend to make adjustments using rebass for inputs and text area.
I worked with this component for some time making adjustments and seeing how the changes were rendered in the browser.  Nothing is broken, but I would like to work with a teammate to get feedback on how I can use the Flex, Text Area, and Input features …
> worked on text area with styled components

- frontend/components/forms/InputArea.tsx
- frontend/components/forms/TextArea.tsx
Tested to make sure input field displays in browser.
> Pull Detail - Input Area

- backend/README.md
Adds server/endpoint documentation to server README.md
> Adds server/endpoint documentation to server README.md

- frontend/components/Navbar/NavBar.tsx
- frontend/pages/_app.tsx
I created a simple NavBar component, no functionality at the moment just wanted to get it in before the presentation. 
expected)
> Class cards

- frontend/components/Counter.tsx
- frontend/components/Layout.tsx
- frontend/components/Students/StudentBar.tsx
- frontend/components/boxes/quizBox/quizBox.tsx
- frontend/components/sidebar/sidebar.tsx
- frontend/now.json
- frontend/package.json
- frontend/pages/_app.tsx
- frontend/pages/classes.tsx
- frontend/pages/index.tsx
We should try to stay away from testing out our components by throwing them in the _app.tsx file :). Made a Layout component that wraps our pages.
> move components from _app.tsx to Layout component

- frontend/components/forms/AddStudent.tsx
checked rendering in browser
we are continuing to trouble-shoot together
> built new add student form with mutation

- frontend/components/Layout.tsx
- frontend/components/Meta.tsx
- frontend/components/Navbar/NavBar.tsx
- frontend/components/sidebar/sidebar.tsx
- frontend/pages/billing.tsx
- frontend/pages/classes.tsx
- frontend/pages/index.tsx
- frontend/pages/quizzes.tsx
- frontend/pages/settings.tsx
- Restructures Layout to use flexbox to control page component placement
- Removes display `fixed` and z-index from SideBar
- Implements global styles in Meta component; adds reset styling
- Removes all `Unknown` components from ReactDOM tree. (please only use named exports for future frontend code)
- border-radius: 50% makes a box a circle
> Billing presentation

- frontend/components/Layout.tsx
Quick patch to fix development import of SideBar
> quick patch of SideBar import; missing semicolon

- frontend/components/forms/AddStudent.tsx
Just so we have a space to test out components
> Test Page for Trying out Components

- backend/api/Mailer.js
- backend/package.json
I am adding the sendgrid package, so please make sure to run yarn.  This PR adds a file called Mailer.js which is essentially a class we can use to communicate with SendGrid.  See [https://github.com/StephenGrider/FullstackReactCode/blob/master/server/services/Mailer.js] (https://github.com/StephenGrider/FullstackReactCode/blob/master/server/services/Mailer.js) for reference.  Please feel free to modify the current code in this file.  I'd like some support with the helper function that takes in a list of recipients. API key for sendgrid is in our evernote notebook. 
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test …
> Sendgrid Mailer

- frontend/components/forms/AddClass.tsx
- frontend/components/forms/AddStudent.tsx
- frontend/pages/protected.js
This is just a follow up that reformats the sample forms to use the right data for the mutations to insert on the backend, note that currently a teacher has to be added manually until the redirect page checks if user is table and adds them if need be.
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] Complete, tested, ready to review and merge
- [ x] Test A - used to insert some classes and students to classes and then check tables on back end to ensure they went through
- [x ] My code follows the style guidelines of this project
- [x ] I have …
> mutations in form samples now work with updated backend permissions

- frontend/components/design-system/primitives.ts
- frontend/components/sidebar/sidebar.tsx
> fo da last time!

- frontend/hocs/securePage.js
- frontend/pages/classes/class.tsx
- frontend/pages/classes/index.tsx
- frontend/pages/home.tsx
- frontend/pages/quizzes/index.tsx
Modified auth to redirect instead of displaying not authorized div.
Secured pages that should be secured
> Secure pages

- frontend/components/Students/StudentBar.tsx
- frontend/components/design-system/primitives.ts
- frontend/components/forms/AddStudent.tsx
- frontend/pages/classes/class.tsx
- frontend/pages/classes/index.tsx
I added to the classes page the add a class form, and then on an individual class page I have added in the add a student form and tooled around with the form stylings for the student roster(very basic styling at this point). And then started the beginnings of gathering all of the quizzes that are connected to the class by the id, not far on that just started creating basic components for it like a container and holder.
> Classes class page

- frontend/components/Billing/Checkout.tsx
- frontend/components/Billing/SplitForm.tsx
- frontend/components/Navbar/NavBar.tsx
- frontend/components/design-system/primitives.ts
- frontend/pages/billing.tsx
mini-merge into billing-responsive
> Billing responsive mini branch

- frontend/components/Billing/Checkout.tsx
- frontend/components/Billing/SplitForm.tsx
- frontend/components/Navbar/NavBar.tsx
- frontend/components/design-system/primitives.ts
- frontend/components/sidebar/sidebar.tsx
- frontend/pages/billing.tsx
- uses primitives for styling
- adds form validation, visual feedback and displays error messages to the user
- disables submit button until form passes validation (very rough implementation)
> Billing responsive

- frontend/components/Students/StudentBar.tsx
- frontend/components/boxes/classBox/classBox.tsx
- frontend/components/design-system/primitives.ts
- frontend/components/forms/AddStudent.tsx
- frontend/pages/auth/signed-in.js
- frontend/pages/classes/class.tsx
- frontend/pages/classes/index.tsx
So in this PR I have worked out most of the class/classes pages, so you are able to add a class to you list and then access that class and then populate the class with students without putting in the id for the student.
> Class quiz page

- frontend/components/sidebar/sidebar.tsx
- frontend/pages/student.tsx
This page should show some information relevant to students and provide students with a direction for taking a quiz that has been assigned to them. 
> Student View 

- frontend/components/StudentView/StudentQuiz.tsx
- frontend/components/StudentView/StudentView.tsx
- frontend/components/design-system/primitives.ts
- frontend/pages/student/index.tsx
- frontend/pages/student/studentquiz.tsx
Finalized a layout for student view.  Needs functionality and data.
> better student view layout

- frontend/components/boxes/ClassQuizzes.tsx
- frontend/components/boxes/QuizElement.tsx
- frontend/components/boxes/classBox/classBox.tsx
- frontend/components/design-system/primitives.ts
- frontend/pages/classes/class.tsx
- frontend/pages/classes/index.tsx
The classes page is just about complete, all I will need to implement next is the adding a quiz function now needs to be connected with the backend. Currently, it is set up locally so will only add a quiz locally to the individual class. 
> Quizzes to class

- frontend/components/StudentView/StudentQuiz.tsx
> Updates To Student Quiz

- frontend/components/StudentView/StudentQuiz.tsx
> small changes to StudentQuiz

- backend/student-proxy/index.js
- backend/student-proxy/package.json
Adds the student proxy micro server code, still needs the other mutations but currently serves the first query request
- [] My code follows the style guidelines of this project
> Student proxy

- backend/token-mailer/index.js
- backend/token-mailer/package.json
Adds the token mailer micro server code, still needs the commands finished for mailing service but currently serves the test token
- [] My code follows the style guidelines of this project
> Token mailer

- frontend/pages/student/index.tsx
- frontend/utils/auth.js
Modifies the student landing page to grab token from url and store as cookie, then redirects user to specific quiz
- [] My code follows the style guidelines of this project
> Student landing

- frontend/components/Billing/SplitForm.tsx
- frontend/components/StudentView/StudentQuiz.tsx
- frontend/components/design-system/primitives.ts
- frontend/pages/quiz-taking/index.tsx
- frontend/pages/quiz-taking/quiz-taking.tsx
- frontend/utils/withData.ts
- adds major/minor question student quiz ui; buggy but progress; needs major refactor to clean code
> Student view

- backend/student-proxy/index.js
Expands on the student-proxy server, adding the ability to transform passed data into the required student mutations
> Added insert major question and insert minor question mutations

- frontend/components/Students/StudentBar.tsx
- frontend/components/boxes/ClassQuizzes.tsx
- frontend/components/design-system/primitives.ts
- frontend/pages/classes/class.tsx
The class page is very close to being complete, just needs some refactoring about the functionality.
The functionality of adding a quiz to a class needs some work.
> Responsive design

- frontend/components/LandingPage/GetStarted.tsx
- frontend/pages/index.tsx
just setting up basic structure
> started working on GetStarted component and added imports to index

- frontend/hocs/unsecurePage.js
- frontend/pages/home.tsx
- frontend/pages/index.tsx
Adds redirect from landing page to quizzes if signed in. Also fixes refresh bug on /home.
> Landing redirect

- frontend/components/boxes/ClassQuizzes.tsx
- frontend/components/boxes/QuizElement.tsx
- frontend/components/forms/AddClass.tsx
- frontend/components/forms/AddStudent.tsx
- frontend/mutations/index.ts
- frontend/pages/classes/class.tsx
- frontend/pages/classes/index.tsx
- frontend/queries/index.ts
Fixes mutation updates to properly work and refresh the page components properly.
> Add class bugfix

- frontend/components/forms/AddQuiz.tsx
Small bugfix, no change beyond that.
> fix bug where submission fails if there's no minor question

- frontend/components/Navbar/AvatarPopup.tsx
- frontend/components/Navbar/NavBar.tsx
- adds animated popup to `AvatarImg` onClick (Student, Settings, Log Off)
- [*] Test A: local testing
> adds popup to NavBar Avatar

- frontend/components/Billing/SplitForm.tsx
> Form shadow

- frontend/components/LandingPage/GetStarted.tsx
- frontend/components/landingPage-top/topLandingPage.tsx
> adds popping GetStarted; isolated stying change

- frontend/components/LandingPage/Footer.tsx
- frontend/components/LandingPage/Testimonials.tsx
- frontend/components/design-system/primitives.ts
- frontend/components/landingPage-top/topLandingPage.tsx
Fixed some of the things Nick had said this morning.
-Header
-Pro Plan (Cesar)
-Smaller and less colored boxes
> Finishing up landing

- frontend/components/Navbar/AvatarPopup.tsx
- frontend/components/StudentView/MajorQuestion.tsx
- frontend/components/StudentView/MinorQuestion.tsx
- frontend/components/StudentView/StudentQuiz.tsx
minor styling fix and updates token for demo
> student quiz view input field alignment fix and dropShadow addition

- frontend/components/Layout.tsx
- frontend/components/boxes/QuizElement.tsx
- frontend/components/boxes/classBox/classBox.tsx
- frontend/components/boxes/studentBox/studentBox.tsx
- frontend/components/design-system/primitives.ts
- frontend/pages/classes/class.tsx
- frontend/pages/classes/index.tsx
- frontend/pages/quizzes/index.tsx
- frontend/utils/theme.ts
> Class layout

- frontend/components/LandingPage/Footer.tsx
Fixed all that needed to be fixed according to the UI UX meeting on the landing page, mostly the same, just the footer has changed a bit. 
-flex-wrap fixed
-about us fixed
> Landing fixes

- backend/student-proxy/index.js
- frontend/components/Navbar/AvatarPopup.tsx
- frontend/components/StudentView/StudentQuiz.tsx
- frontend/pages/student/studentquiz.tsx
- updates test student token
- student quiz view writes quiz result to score table on completion 
> student quiz view writes to score table on quiz completion

- frontend/components/Modal/index.tsx
- frontend/components/Navbar/NavBar.tsx
- frontend/components/boxes/quizBox/quizBox.tsx
- frontend/components/boxes/studentBox/studentBox.tsx
- frontend/components/design-system/primitives.ts
- frontend/components/forms/AddStudent.tsx
- frontend/components/sidebar/sidebar.tsx
- frontend/pages/classes/class.tsx
> Implement modals

- backend/student-proxy/index.js
- frontend/components/Meta.tsx
- frontend/components/Navbar/AvatarPopup.tsx
- frontend/components/Navbar/NavBar.tsx
- frontend/components/boxes/ClassQuizzes.tsx
- frontend/mutations/index.ts
- frontend/package.json
- frontend/pages/classes/class.tsx
- frontend/static/datepicker.css
- frontend/yarn.lock
> New datepicker

- frontend/components/Navbar/NavBar.tsx
- frontend/components/SideBar.tsx
- frontend/components/boxes/addBox/addBox.tsx
- frontend/components/design-system/primitives.ts
- frontend/pages/classes/class.tsx
- frontend/pages/classes/index.tsx
- frontend/pages/quizzes/index.tsx
-side and nav bar fixed
-hover effects added to the addBox and avatar
-breadcrumbs 
> Nav side bar

- backend/student-proxy/index.js
- frontend/components/StudentView/StudentQuiz.tsx
- Simple fix that adds `total` quiz score to score table
> Fix student quiz total score

- frontend/components/Navbar/NavBar.tsx
- frontend/components/forms/EditQuiz/MajorQuestionForm.tsx
- frontend/components/forms/EditQuiz/index.tsx
-fixed the edit quiz page styling the same as the add quiz page. 
-there are no merge conflicts
> Edit page styling

- frontend/components/boxes/ClassQuizzes.tsx
makes reactdatepicker input look perty
> React datepicker custom input style

- frontend/components/forms/EditQuiz/MinorAnswersForm.tsx
- frontend/mutations/index.ts
- hotfix to allow for multiple update mutations on major/minor answers; fix employed aliases
> Major minor answer update mutations hotfix

- frontend/components/boxes/quizBox/quizBox.tsx
- frontend/components/forms/EditQuiz/MajorQuestionForm.tsx
- frontend/components/forms/EditQuiz/MinorQuestionForm.tsx
- fixed visibility toggle on all edit quiz buttons
> Fix update quiz button

- backend/add-credit/index.js
- frontend/components/Billing/SplitForm.tsx
- frontend/components/Layout.tsx
- frontend/components/Navbar/AvatarPopup.tsx
- frontend/components/Navbar/NavBar.tsx
- frontend/components/forms/EditQuiz/MajorQuestionForm.tsx
> credit added to navbar ... hackiest hack i've ever hacked ... but works

- backend/add-credit/index.js
- frontend/components/StudentView/MajorQuestion.tsx
- frontend/components/StudentView/MinorQuestion.tsx
- frontend/components/StudentView/StudentQuiz.tsx
- frontend/utils/theme.ts
simple score button feedback on right/wrong answer submission. placeholder feedback until i can do better.
> quiz feedback ...  simple button feedback until my mind improves

- frontend/components/boxes/ClassQuizzes.tsx
- quick fix to eliminate console error on prop-type validation failure
> fixes console error on selected prop-type in datepicker

- frontend/components/forms/AddQuiz.tsx
Just changing the names of the questions in the add-quiz form to "Primary" and "Follow-up"
> changed language in add-quiz form to Primary and Follow up

- frontend/components/StudentResults.tsx
- frontend/components/boxes/ClassQuizzes.tsx
- frontend/queries/index.ts
Minor bugfix to correct some mistakes
-update on student results accidentally removed quiz name from query, added back in
-datepicker was updated to fill in already assigned days, but would set date to sometime in 1969 for any that didn't already have a date. Switched to useEffect to check if dueDate is being passed in at start, then updating it.
> minor bugfixes

- frontend/components/LandingPage/Footer.tsx
- frontend/components/Navbar/NavBar.tsx
-all I did was remove a green line from the landing that was in the footer
> Video branch

- backend/add-credit/index.js
- backend/hasura-test/index.js
- backend/token-mailer/index.js
Final changes to the mailer. Query to get the quizzes to go out now pulls properly, loops through and sends the emails, then updates the quiz to say that it's been sent out.
> Final mailer changes

- README.md
- frontend/components/StudentResults.tsx
Added links to the licenses for images used on landing page.
> Credits for images in Readme

- frontend/components/design-system/primitives.ts
-just a quick fix on the landing
> Landing last fix

- frontend/components/Billing/SplitForm.tsx
- frontend/components/StudentView/StudentQuiz.tsx
- frontend/pages/student/studentquiz.tsx
quick fix to switch links from localhost to deployed
> Switched links to point to deployed rather than localhost
